---
title: 'ggplot2: Facets (Combine multiple plots)'
date: '2016-07-08'
slug: ggplot2-facets-combine-multiple-plots
topics:
  - ggplot2
tags:
  - ggplot2
  - visualization
draft: yes
---

# Introduction

This is the 13th post in the series **Elegant Data Visualization with ggplot2**. In the previous [post](https://rsquaredacademy.github.io/blog/post/ggplot2-facets/), we learnt the `stat_*()` family of functions. In this post, we will learn about faceting i.e. combining plots.

```{r facet, echo=FALSE, eval=TRUE, results='hide', message=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r import, echo=FALSE, eval=TRUE, results='hide', message=FALSE}
ecom <- readr::read_csv('https://raw.githubusercontent.com/rsquaredacademy/datasets/master/web.csv')
```

We will continue to use the ecommerce data. You can download it from [here](https://github.com/rsquaredacademy/datasets/blob/master/web.csv) or import directly using the readr package.

```{r import2, echo=FALSE, eval=FALSE, results='hide', message=FALSE}
ecom <- readr::read_csv('https://raw.githubusercontent.com/rsquaredacademy/datasets/master/web.csv')
```

```{r facet1}
ggplot(ecom, aes(n_pages, duration)) + 
  geom_point() +
  facet_grid(. ~ device)
```

```{r facet2}
ggplot(ecom, aes(n_pages, duration)) + 
  geom_point() +
  facet_grid(device ~ .)
```

```{r facet3}
ggplot(ecom, aes(n_pages, duration)) + 
  geom_point() +
  facet_grid(purchase ~ device)
```

```{r facet4}
ggplot(ecom, aes(n_pages, duration)) + 
  geom_point() +
  facet_grid(device ~ purchase)
```

```{r facet5}
ggplot(ecom, aes(n_pages, duration, color = factor(device))) +
  geom_point() + 
  facet_grid(. ~ device, scales = "free")
```

```{r facet6}
ggplot(ecom, aes(n_pages, duration)) + 
  geom_point() + 
  facet_grid(device ~ purchase, switch = "both") 
```

```{r facet7}
ggplot(ecom, aes(n_pages, duration)) +
  geom_point() +
  facet_wrap(~device)
```

```{r facet8}
ggplot(ecom, aes(n_pages, duration)) +
  geom_point() +
  facet_wrap(~device, nrow = 2)
```

```{r facet9}
ggplot(ecom, aes(n_pages, duration)) +
  geom_point() +
  facet_wrap(~device, nrow = 3)
```

```{r facet10}
ggplot(ecom, aes(n_pages, duration)) +
  geom_point() +
  facet_wrap(~device + purchase)
```

```{r facet11}
ggplot(ecom, aes(n_pages, duration)) +
  geom_point() +
  facet_wrap(c("device", "purchase"))
```

```{r facet12}
ggplot(ecom, aes(n_pages, duration)) +
  geom_point() +
  facet_wrap(~device, scales = "free")
```


